-- ═══════════════════════════════════════════════════════════════════════
-- Seed data. Safe to run once on a fresh project (supabase db reset runs it
-- automatically). Demo projects are flagged is_demo = true and are shown
-- with a visible "Demonstration" label; replace them from /admin.
-- ═══════════════════════════════════════════════════════════════════════

-- Organisation details start empty: the site shows clearly marked placeholders
-- until an administrator fills them in under Admin → Settings.
insert into public.site_settings (key, value) values ('organisation', jsonb_build_object(
  'email', null, 'phone', null, 'address', null, 'office_hours', null,
  'socials', '{}'::jsonb, 'bank', null, 'mpesa_paybill', null,
  'sda_logo_url', null, 'partnership_statement', null
)) on conflict (key) do nothing;

-- Curated gallery (images ship with the site under /public/images/gallery).
insert into public.gallery (title, image_url, thumb_url, category, width, height, credit_author, credit_license, credit_source, featured, published, display_order) values
  ('Modernist sanctuary under an evening sky', '/images/gallery/architecture-modernist-sanctuary.webp', '/images/gallery/architecture-modernist-sanctuary-sm.webp', 'architecture', 2400, 1689, 'Historic American Buildings Survey', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Pfeiffer_Chapel_HABS,_FLA,53-LAKE,1A-14.jpg', true, true, 0),
  ('A crown of white concrete rising to the cross', '/images/gallery/architecture-crown-church.webp', '/images/gallery/architecture-crown-church-sm.webp', 'architecture', 2400, 1607, 'Anthony22 at en.wikipedia', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Saint_Francis_of_Assisi_Chapel_2006.jpg', true, true, 1),
  ('Timber and glass gable facade', '/images/gallery/architecture-glass-gable.webp', '/images/gallery/architecture-glass-gable-sm.webp', 'architecture', 2400, 1800, '--Immanuel Giel 09:47, 9 July 2007 (UTC)', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Friedhof_Limburgerhof_01.JPG', false, true, 2),
  ('Contemporary church with free-standing bell frame', '/images/gallery/architecture-bell-frame.webp', '/images/gallery/architecture-bell-frame-sm.webp', 'architecture', 2400, 1599, 'Stefan Oemisch', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:2022_FriedhofTrauerhalle.jpg', false, true, 3),
  ('Glass and brick bell tower', '/images/gallery/architecture-glass-tower.webp', '/images/gallery/architecture-glass-tower-sm.webp', 'architecture', 2400, 1433, 'Halaszo', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:OtaniemiChapel.jpg', false, true, 4),
  ('A slender spire over a modern nave', '/images/gallery/architecture-white-spire.webp', '/images/gallery/architecture-white-spire-sm.webp', 'architecture', 1800, 2400, 'TeWeBs', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:RI_Josua-Stegmann-Kapelle.JPG', false, true, 5),
  ('Low-slung modern sanctuary', '/images/gallery/architecture-low-sanctuary.webp', '/images/gallery/architecture-low-sanctuary-sm.webp', 'architecture', 2400, 1800, 'Kirchenfan', 'CC0', 'https://commons.wikimedia.org/wiki/File:Grassel_Kapelle.jpg', false, true, 6),
  ('Gabled sanctuary with a glazed front', '/images/gallery/architecture-gable-light.webp', '/images/gallery/architecture-gable-light-sm.webp', 'architecture', 2400, 1584, 'Prof. emeritus Hans Schneider (Geyersberg)', 'CC BY 3.0', 'https://commons.wikimedia.org/wiki/File:Gielsdorf_Friedhofkapelle_(01).png', false, true, 7),
  ('Brick church facade crowned with a cross', '/images/gallery/architecture-brick-cross-facade.webp', '/images/gallery/architecture-brick-cross-facade-sm.webp', 'architecture', 2400, 1350, 'MBERABAHIZI', 'CC0', 'https://commons.wikimedia.org/wiki/File:Catholic_Church_in_Muhanga.jpg', false, true, 8),
  ('Domed church above a ceremonial stair', '/images/gallery/architecture-domed-steps.webp', '/images/gallery/architecture-domed-steps-sm.webp', 'architecture', 2400, 1600, 'IGANZE', 'CC0', 'https://commons.wikimedia.org/wiki/File:Catholique_church_in_Rwanda.jpg', false, true, 9),
  ('A pyramidal roof reaching upward', '/images/gallery/architecture-pyramid-roof.webp', '/images/gallery/architecture-pyramid-roof-sm.webp', 'architecture', 2400, 1704, 'Jim Osley', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:St_Albans_,_Seventh_Day_Adventist_Church_-_geograph.org.uk_-_7727226.jpg', false, true, 10),
  ('Concrete nave drawing the eye to the altar', '/images/gallery/interiors-concrete-nave.webp', '/images/gallery/interiors-concrete-nave-sm.webp', 'interiors', 2400, 1743, 'Grantmcunningham', 'CC0', 'https://commons.wikimedia.org/wiki/File:Vaulted_concrete_ceiling,_Notre_Dame_of_Lourdes_Church_(Casablanca).jpg', true, true, 11),
  ('Timber sanctuary and a simple cross', '/images/gallery/interiors-timber-cross.webp', '/images/gallery/interiors-timber-cross-sm.webp', 'interiors', 2400, 1714, 'CEphoto, Uwe Aranas', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Essen_Germany_Interior-of-BMV-Church-01.jpg', true, true, 12),
  ('Modern nave with a wall of coloured glass', '/images/gallery/interiors-coloured-glass.webp', '/images/gallery/interiors-coloured-glass-sm.webp', 'interiors', 2400, 2023, 'Diliff', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Coventry_Cathedral_Interior,_West_Midlands,_UK_-_Diliff.jpg', false, true, 13),
  ('Bright nave with stained glass at its head', '/images/gallery/interiors-stained-nave.webp', '/images/gallery/interiors-stained-nave-sm.webp', 'interiors', 2400, 1715, 'Bahnfrend', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Cathedral_Basilica_of_the_Holy_Family,_Nairobi,_2025_(03).jpg', false, true, 14),
  ('A large contemporary worship hall', '/images/gallery/interiors-grand-hall.webp', '/images/gallery/interiors-grand-hall-sm.webp', 'interiors', 2400, 1600, 'Ssemmanda will', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:All_Saints_Cathedral,_Kampala._Kampala_Diocese,_Church_of_Uganda_-_Anglican_04.jpg', false, true, 15),
  ('White sanctuary and wooden pews', '/images/gallery/interiors-white-sanctuary.webp', '/images/gallery/interiors-white-sanctuary-sm.webp', 'interiors', 2400, 1600, 'Ssemmanda will', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:All_Saints_Cathedral,_Kampala._Kampala_Diocese,_Church_of_Uganda_-_Anglican_17.jpg', false, true, 16),
  ('Timber chancel lit in warm light', '/images/gallery/interiors-lit-timber.webp', '/images/gallery/interiors-lit-timber-sm.webp', 'interiors', 2400, 1600, 'Bjankuloski06', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Sanctuary_wall_with_suspended_cross,_All_Saints_Church,_Ponsonby.jpg', false, true, 17),
  ('A beam of light falls across the floor', '/images/gallery/interiors-light-beam.webp', '/images/gallery/interiors-light-beam-sm.webp', 'interiors', 1800, 2400, 'Matteo Pappadopoli', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:La_luce_del_rosone.jpg', true, true, 18),
  ('Light rays through a high window', '/images/gallery/interiors-light-rays.webp', '/images/gallery/interiors-light-rays-sm.webp', 'interiors', 1590, 2400, 'Jules & Jenny from Lincoln, UK', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Barton_Upon_Humber,_St_Mary%27s_church_(26965398389).jpg', false, true, 19),
  ('A long nave beneath a coffered ceiling', '/images/gallery/interiors-long-nave.webp', '/images/gallery/interiors-long-nave-sm.webp', 'interiors', 2400, 1596, 'Didier Descouens', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Church_of_the_Eremitani_(Padua)_-_Interior.jpg', false, true, 20),
  ('Stone walls and long pews ready for worship', '/images/gallery/interiors-stone-pews.webp', '/images/gallery/interiors-stone-pews-sm.webp', 'interiors', 2400, 1800, 'Hanay', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:St._Pierre_Church_near_Kibuye_where_people_were_murdered_in_1994_during_the_Rwandan_genocide_-_inside_(1).jpg', false, true, 21),
  ('Carrying a block to the site', '/images/gallery/construction-carrying-block.webp', '/images/gallery/construction-carrying-block-sm.webp', 'construction', 2400, 1600, 'Biva2017', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Construction-women.jpg', true, true, 22),
  ('Every stone carried by hand', '/images/gallery/construction-carrying-stone.webp', '/images/gallery/construction-carrying-stone-sm.webp', 'construction', 2400, 1600, 'Biva2017', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Slum_construction.jpg', false, true, 23),
  ('Blockwork walls taking shape', '/images/gallery/construction-blockwork.webp', '/images/gallery/construction-blockwork-sm.webp', 'construction', 2400, 1800, 'Africa1718', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Construction_Of_Office_in_Kenya.jpg', false, true, 24),
  ('Laying blocks course by course', '/images/gallery/construction-laying-blocks.webp', '/images/gallery/construction-laying-blocks-sm.webp', 'construction', 2400, 1607, 'Okhaifo', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Bricklayer_at_work.jpg', false, true, 25),
  ('Mixing mortar on site', '/images/gallery/construction-mixing-mortar.webp', '/images/gallery/construction-mixing-mortar-sm.webp', 'construction', 2005, 2400, 'Albertoblaq', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Bricklaying.png', false, true, 26),
  ('Light through a new window opening', '/images/gallery/construction-window-light.webp', '/images/gallery/construction-window-light-sm.webp', 'construction', 2400, 2067, 'Kimathinjoki', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Turbaned_mason.jpg', false, true, 27),
  ('A concrete frame rising', '/images/gallery/construction-rising-frame.webp', '/images/gallery/construction-rising-frame-sm.webp', 'construction', 2400, 1800, 'Eyibeauty Oyelowo', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Bricklayers_on_site,_Kwara_State,_Nigeria.jpg', false, true, 28),
  ('Setting the foundation', '/images/gallery/construction-foundation.webp', '/images/gallery/construction-foundation-sm.webp', 'construction', 2400, 1607, 'Kenogenic', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Nigerian_bricklayers_(4).jpg', false, true, 29),
  ('Scaffolding inside a church under restoration', '/images/gallery/renovation-scaffold-interior.webp', '/images/gallery/renovation-scaffold-interior-sm.webp', 'renovation', 2400, 1600, 'Arne Müseler', 'CC BY-SA 3.0 de', 'https://commons.wikimedia.org/wiki/File:Adnet_kirche_church_restauration_1.jpg', false, true, 30),
  ('Restoring arches and plasterwork', '/images/gallery/renovation-scaffold-arches.webp', '/images/gallery/renovation-scaffold-arches-sm.webp', 'renovation', 2400, 1600, 'Arne Müseler', 'CC BY-SA 3.0 de', 'https://commons.wikimedia.org/wiki/File:Adnet_kirche_church_restauration_2.jpg', false, true, 31),
  ('Restoring historic brickwork', '/images/gallery/renovation-brick-restoration.webp', '/images/gallery/renovation-brick-restoration-sm.webp', 'renovation', 2400, 1800, 'MOs810', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MOs810,_WG_2016_47,_Dolnoslaskie_Zakamarki_III_(Saint_Lazarus_church_in_Wroc%C5%82aw,_renovatio_2016).jpg', false, true, 32),
  ('Scaffolding against an old brick wall', '/images/gallery/renovation-scaffold-wall.webp', '/images/gallery/renovation-scaffold-wall-sm.webp', 'renovation', 2400, 1600, 'A. Davey from Where I Live Now: Pacific Northwest', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Church_of_Bet_Meskel_(House_of_the_Cross),_Lalibela,_Ethiopia_(3223537258).jpg', false, true, 33),
  ('An open Bible on its stand', '/images/gallery/details-bible-stand.webp', '/images/gallery/details-bible-stand-sm.webp', 'details', 2400, 1594, 'Wilfredor', 'CC0', 'https://commons.wikimedia.org/wiki/File:Open_Bible_in_the_Church_of_the_ports_of_Altagracia.jpg', false, true, 34),
  ('Scripture and study', '/images/gallery/details-bible-pen.webp', '/images/gallery/details-bible-pen-sm.webp', 'details', 2400, 1600, 'Ryk Neethling from Melbourne, Australia', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Open_Bible_with_pen_(4543060842).jpg', false, true, 35),
  ('Pews in afternoon light', '/images/gallery/details-pews-light.webp', '/images/gallery/details-pews-light-sm.webp', 'details', 2400, 1600, 'Acabashi', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Beauchamp_Roding_-_St_Botolph%27s_Church_-_Essex_England_-_nave_north_tiered_oak_pews.jpg', false, true, 36),
  ('Light across cast concrete', '/images/gallery/details-concrete-detail.webp', '/images/gallery/details-concrete-detail-sm.webp', 'details', 2400, 2400, 'seier+seier', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Gottfried_b%C3%B6hm,_kolumba_chapel_extension_1956_(3460863882).jpg', false, true, 37),
  ('The open Word', '/images/gallery/details-open-bible.webp', '/images/gallery/details-open-bible-sm.webp', 'details', 2400, 1800, 'Leon Brooks', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Holy_bible_book.jpg', false, true, 38),
  ('A congregation gathered in worship', '/images/gallery/community-congregation.webp', '/images/gallery/community-congregation-sm.webp', 'community', 2400, 1589, 'Look4Faith', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Christian_Funeral_Service_in_Zimbabwe_where_family_and_community_gather_to_honor_the_deceased_through_religious_and_cultural_practices.jpg', false, true, 39),
  ('A full sanctuary', '/images/gallery/community-full-sanctuary.webp', '/images/gallery/community-full-sanctuary-sm.webp', 'community', 2400, 1351, 'Symphorien Bouassi', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:%C3%89glise_%C3%89vang%C3%A9lique_Baptiste_de_Berberati-centre_culte.jpg', false, true, 40),
  ('Voices raised in praise', '/images/gallery/community-choir.webp', '/images/gallery/community-choir-sm.webp', 'community', 2400, 1570, 'Nibeza', 'CC0', 'https://commons.wikimedia.org/wiki/File:Worshiping_God_in_Rwanda.jpg', true, true, 41),
  ('Children at a worship service', '/images/gallery/community-children-service.webp', '/images/gallery/community-children-service-sm.webp', 'community', 2400, 1600, 'Michael Denne', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:AAC_Worshippers.jpg', false, true, 42),
  ('Kneeling in prayer', '/images/gallery/community-prayer.webp', '/images/gallery/community-prayer-sm.webp', 'community', 2400, 1600, 'Aimtoba', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Celestialnism_01.jpg', false, true, 43),
  ('Walking together to church', '/images/gallery/community-walking-together.webp', '/images/gallery/community-walking-together-sm.webp', 'community', 2400, 1802, 'Adam Jones, Ph.D.', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Street_Scene_after_Sunday_Morning_Church_-_Rubavu-Gisenyi_-_Rwanda.jpg', false, true, 44),
  ('Sharing the communion emblems', '/images/gallery/community-communion.webp', '/images/gallery/community-communion-sm.webp', 'community', 2400, 1541, 'Tish Madesh', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Easter_Holy_Communion_in_church.jpg', false, true, 45),
  ('Joy that outlasts walls', '/images/gallery/outreach-smiling-child.webp', '/images/gallery/outreach-smiling-child-sm.webp', 'outreach', 2400, 1600, 'Trocaire from Ireland', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Kibera13_(Kenya_1)_(7180347921).jpg', true, true, 46),
  ('A shared meal', '/images/gallery/outreach-shared-meal.webp', '/images/gallery/outreach-shared-meal-sm.webp', 'outreach', 2400, 1800, 'Nicor', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Nyota,_Kenya_02.jpg', false, true, 47),
  ('A classroom full of possibility', '/images/gallery/outreach-classroom.webp', '/images/gallery/outreach-classroom-sm.webp', 'outreach', 2400, 1594, 'D. Willetts', 'CC BY-SA 3.0 igo', 'https://commons.wikimedia.org/wiki/File:(2011_Education_for_All_Global_Monitoring_Report)_-School_children_in_Kakuma_refugee_camp,_Kenya_1.jpg', false, true, 48),
  ('Children running across the field', '/images/gallery/outreach-running-children.webp', '/images/gallery/outreach-running-children-sm.webp', 'outreach', 2400, 1349, 'Onlyonestef', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Girls_compete_in_a_7_lap_race_during_high_school_first_term_games_in_Machakos,_Kenya.jpg', false, true, 49),
  ('Neighbours gathering outdoors', '/images/gallery/outreach-gathering.webp', '/images/gallery/outreach-gathering-sm.webp', 'outreach', 2400, 1800, 'Agoni Abraham', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Volunteers_in_Africa.jpg', false, true, 50),
  ('Schoolchildren together', '/images/gallery/outreach-school-children.webp', '/images/gallery/outreach-school-children-sm.webp', 'outreach', 2400, 1800, 'Oertherdb', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:School_children_amazed_by_flowing_water_from_pipe_stand_in_Otho_Abwao_Kenya.jpg', false, true, 51),
  ('A young learner at his desk', '/images/gallery/outreach-young-learner.webp', '/images/gallery/outreach-young-learner-sm.webp', 'outreach', 2400, 1594, 'Master Sgt. Jeremy Lock', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Community_Assistance_Volunteers_DVIDS96949.jpg', false, true, 52),
  ('Volunteers making building blocks', '/images/gallery/volunteers-block-making.webp', '/images/gallery/volunteers-block-making-sm.webp', 'volunteers', 1800, 2400, 'Goodymeraj', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:A_bricklayer_moulding_blocks.jpg', false, true, 53),
  ('Volunteers painting a classroom', '/images/gallery/volunteers-painting.webp', '/images/gallery/volunteers-painting-sm.webp', 'volunteers', 2400, 1463, 'Master Sgt. Jeremy Lock', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Community_Assistance_Volunteers_DVIDS96943.jpg', false, true, 54);

-- Demonstration projects (clearly labelled on the website).
with p as (
  insert into public.projects (title, slug, summary, description, category, location, status, cover_image, objectives, featured, published, is_demo) values
  ('New Sanctuary Construction', 'demo-new-sanctuary', 'Sample layout for a ground-up church construction project.', 'This is a demonstration entry that shows how a construction project will appear on the website. Once the organisation publishes a real project from the admin dashboard, its verified description, location, photographs and progress updates will replace this text.', 'construction', 'Location to be confirmed', 'ongoing', '/images/gallery/construction-rising-frame.webp', array['Example objective — complete foundation and structural frame','Example objective — enclose the building and install roofing','Example objective — finish interior and dedicate the sanctuary'], true, true, true),
  ('Sanctuary Renovation', 'demo-sanctuary-renovation', 'Sample layout for restoring an existing church building.', 'A demonstration renovation project. Real renovation projects will document the condition of the existing structure, the planned works and verified progress, all managed from the admin dashboard.', 'renovation', 'Location to be confirmed', 'planned', '/images/gallery/renovation-scaffold-arches.webp', array['Example objective — structural assessment','Example objective — roof and wall repairs','Example objective — interior refurbishment'], true, true, true),
  ('Community Outreach Programme', 'demo-community-outreach-centre', 'Sample layout for a church-led community initiative.', 'A demonstration community initiative. This is where the organisation will describe real outreach programmes run through partner congregations once details are published.', 'community', 'Location to be confirmed', 'planned', '/images/gallery/outreach-shared-meal.webp', array['Example objective — identify community needs with the local church','Example objective — launch the programme'], true, true, true),
  ('Chapel Completion', 'demo-completed-chapel', 'Sample layout for a completed project.', 'A demonstration of how a completed project and its dedication will be presented.', 'construction', 'Location to be confirmed', 'completed', '/images/gallery/interiors-timber-cross.webp', array['Example objective — dedication service'], false, true, true)
  returning id, slug
)
insert into public.project_images (project_id, image_url, caption, display_order)
select p.id, i.url, 'Illustrative image', i.ord from p join (values
  ('demo-new-sanctuary', '/images/gallery/construction-laying-blocks.webp', 0),
  ('demo-new-sanctuary', '/images/gallery/construction-blockwork.webp', 1),
  ('demo-new-sanctuary', '/images/gallery/construction-mixing-mortar.webp', 2),
  ('demo-new-sanctuary', '/images/gallery/construction-foundation.webp', 3),
  ('demo-sanctuary-renovation', '/images/gallery/renovation-scaffold-interior.webp', 0),
  ('demo-sanctuary-renovation', '/images/gallery/renovation-brick-restoration.webp', 1),
  ('demo-sanctuary-renovation', '/images/gallery/renovation-scaffold-wall.webp', 2)
) as i(slug, url, ord) on i.slug = p.slug;

insert into public.project_updates (project_id, title, content)
select id, 'Example update', 'Project updates published from the admin dashboard will appear here as a timeline, with optional photographs.'
from public.projects where slug = 'demo-new-sanctuary';

-- Starter FAQs (mirrors src/data/faqs.ts; edit them in Admin → FAQs).
insert into public.faqs (category, question, answer, display_order) values
  ('About us', 'What is Golden Blocks Mission?', 'A nonprofit Christian organisation that builds and renovates churches and supports the Gospel, working with the Seventh-day Adventist Church in the North East Kenya Field.', 1),
  ('About us', 'What does the name “Golden Blocks” mean?', 'Gold is our finest, freely offered to God. Blocks are the material of His house.', 2),
  ('Giving', 'How can I give?', 'On the Donate page: M-Pesa, Visa or Mastercard, or bank transfer.', 3),
  ('Giving', 'Is giving online secure?', 'Yes. Cards are processed by Paystack, and each gift is confirmed by the payment provider before it is recorded.', 4),
  ('Giving', 'Can I choose what my gift supports?', 'Yes. Choose an area of work or a specific project when you give.', 5),
  ('Giving', 'Can I give every month?', 'Yes, by card. M-Pesa gifts are one-time.', 6),
  ('Giving', 'Will I receive a receipt?', 'You get a confirmation email once your payment is verified. Official receipts: to be confirmed.', 7),
  ('Getting involved', 'How else can I help besides giving money?', 'Give materials, volunteer, offer professional skills, fundraise or pray. See Get Involved.', 8),
  ('Getting involved', 'Can my church or business partner with you?', 'Yes. Send a partnership enquiry and our team will reply.', 9),
  ('Getting involved', 'How does sponsorship work?', 'Choose a programme on the Sponsorship page and send an enquiry.', 10),
  ('Projects', 'How can I follow a project’s progress?', 'Each project page has photos and progress updates.', 11),
  ('Contact', 'How do I contact the team?', 'Use the form on the Contact page.', 12);
