-- ═══════════════════════════════════════════════════════════════════════
-- Seed data. Safe to run once on a fresh project (supabase db reset runs it
-- automatically). Demo projects are flagged is_demo = true and are shown
-- with a visible "Demonstration" label; replace them from /admin.
-- ═══════════════════════════════════════════════════════════════════════

-- Organisation details start empty: the site shows clearly marked placeholders
-- until an administrator fills them in under Admin → Settings.
insert into public.site_settings (key, value) values ('organisation', jsonb_build_object(
  'email', null, 'phone', null, 'address', null, 'office_hours', null,
  'socials', '{}'::jsonb, 'bank', null, 'mpesa_paybill', null,
  'sda_logo_url', null, 'partnership_statement', null
)) on conflict (key) do nothing;

-- Curated gallery (images ship with the site under /public/images/gallery).
insert into public.gallery (title, image_url, thumb_url, category, width, height, credit_author, credit_license, credit_source, featured, published, display_order) values
  ('Goshen Seventh-day Adventist Church, Sabah, Malaysia', '/images/gallery/architecture-modernist-sanctuary.webp', '/images/gallery/architecture-modernist-sanctuary-sm.webp', 'architecture', 2400, 1600, 'CEphoto, Uwe Aranas', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Goshen_Kota-Marudu_Sabah_Seventh_Day-Adventist-Church-Goshen-01.jpg', true, true, 0),
  ('Seventh-day Adventist Church, Thornleigh, Sydney', '/images/gallery/architecture-crown-church.webp', '/images/gallery/architecture-crown-church-sm.webp', 'architecture', 2400, 1558, 'Sardaka', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:(1)Seventh_Day_Adventist_Church_Thornleigh.jpg', true, true, 1),
  ('First Seventh-day Adventist Church, Kimberley, South Africa', '/images/gallery/architecture-glass-gable.webp', '/images/gallery/architecture-glass-gable-sm.webp', 'architecture', 2400, 1800, 'SDAHeritage', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Kimberley_SDA_Church_Beaconsfield.jpg', false, true, 2),
  ('Capital Memorial Seventh-day Adventist Church, Washington, D.C.', '/images/gallery/architecture-bell-frame.webp', '/images/gallery/architecture-bell-frame-sm.webp', 'architecture', 2400, 1800, 'Dclemens1971', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Capital_Memorial_Seventh-Day_Adventist_Church_01.jpg', false, true, 3),
  ('Loma Linda University Church, California', '/images/gallery/architecture-glass-tower.webp', '/images/gallery/architecture-glass-tower-sm.webp', 'architecture', 2400, 1350, 'Soberclass', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Loma_linda_university_chapel.jpg', false, true, 4),
  ('Hollywood Spanish Seventh-day Adventist Church, Florida', '/images/gallery/architecture-white-spire.webp', '/images/gallery/architecture-white-spire-sm.webp', 'architecture', 2400, 1799, 'Phillip Pessar from Miami, USA', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Seventh-day_Adventist_Church_in_Hollywood,_Florida.jpg', false, true, 5),
  ('Camp Hill Seventh-day Adventist Church, Birmingham', '/images/gallery/architecture-low-sanctuary.webp', '/images/gallery/architecture-low-sanctuary-sm.webp', 'architecture', 2400, 1200, 'User:Hassocks5489', 'CC0', 'https://commons.wikimedia.org/wiki/File:Camp_Hill_Seventh-day_Adventist_Church,_Camp_Hill,_Bordesley_(August_2024)_(1).jpg', false, true, 6),
  ('Adventist church in Hof, Germany', '/images/gallery/architecture-gable-light.webp', '/images/gallery/architecture-gable-light-sm.webp', 'architecture', 2400, 1560, 'PantheraLeo1359531', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Adventgemeinde_Hof_20220628_HOF05539_20221229000662.png', false, true, 7),
  ('Kyambogo Seventh-day Adventist Church, Kampala, Uganda', '/images/gallery/architecture-brick-cross-facade.webp', '/images/gallery/architecture-brick-cross-facade-sm.webp', 'architecture', 2400, 2314, 'Ssemmanda will', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Kyambogo_Seventh_Day_Adventist_Church_01.jpg', false, true, 8),
  ('Adventist church in Uswahilini, Arusha, Tanzania', '/images/gallery/architecture-domed-steps.webp', '/images/gallery/architecture-domed-steps-sm.webp', 'architecture', 2400, 832, 'Bajcetic', 'CC0', 'https://commons.wikimedia.org/wiki/File:WikiAru239.jpg', false, true, 9),
  ('A pyramidal roof reaching upward', '/images/gallery/architecture-pyramid-roof.webp', '/images/gallery/architecture-pyramid-roof-sm.webp', 'architecture', 2400, 1704, 'Jim Osley', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:St_Albans_,_Seventh_Day_Adventist_Church_-_geograph.org.uk_-_7727226.jpg', false, true, 10),
  ('Galleried sanctuary, Adventist church, Wrocław', '/images/gallery/interiors-concrete-nave.webp', '/images/gallery/interiors-concrete-nave-sm.webp', 'interiors', 2400, 1600, 'Robert Niedźwiedzki', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Ko%C5%9Bci%C3%B3%C5%82_Adwentyst%C3%B3w_Dnia_Si%C3%B3dmego._Ul._D%C4%85browskiego_Wroc%C5%82aw_RN3.jpg', true, true, 11),
  ('Sabbath worship at the Adventist church in Canela, Brazil', '/images/gallery/interiors-timber-cross.webp', '/images/gallery/interiors-timber-cross-sm.webp', 'interiors', 2400, 1350, 'Eugenio Hansen, OFS', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Igreja_Adventista_do_S%C3%A9timo_Dia_(Canela,_Brasil)_2.jpg', true, true, 12),
  ('Painted window, The Mission SDA Church, Leamington Spa', '/images/gallery/interiors-coloured-glass.webp', '/images/gallery/interiors-coloured-glass-sm.webp', 'details', 1560, 2400, 'User:Hassocks5489', 'CC0', 'https://commons.wikimedia.org/wiki/File:The_Mission_Seventh-day_Adventist_Church,_George_Street,_Leamington_Spa_(NHLE_Code_1381292)_(April_2026)_(Painted_Windows)_(1).jpg', false, true, 13),
  ('Sanctuary and gallery, Adventist church, Wrocław', '/images/gallery/interiors-stained-nave.webp', '/images/gallery/interiors-stained-nave-sm.webp', 'interiors', 2400, 1600, 'Robert Niedźwiedzki', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Ko%C5%9Bci%C3%B3%C5%82_Adwentyst%C3%B3w_Dnia_Si%C3%B3dmego._Ul._D%C4%85browskiego_Wroc%C5%82aw_RN1.jpg', false, true, 14),
  ('The apse of The Mission SDA Church, Leamington Spa', '/images/gallery/interiors-grand-hall.webp', '/images/gallery/interiors-grand-hall-sm.webp', 'details', 2400, 1800, 'User:Hassocks5489', 'CC0', 'https://commons.wikimedia.org/wiki/File:The_Mission_Seventh-day_Adventist_Church,_George_Street,_Leamington_Spa_(NHLE_Code_1381292)_(April_2026)_(Interior)_(1).jpg', false, true, 15),
  ('A renewed sanctuary, Adventist church, Wrocław', '/images/gallery/interiors-white-sanctuary.webp', '/images/gallery/interiors-white-sanctuary-sm.webp', 'interiors', 2400, 1695, 'Robert Niedźwiedzki', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Ko%C5%9Bci%C3%B3%C5%82_Adwentyst%C3%B3w_Dnia_Si%C3%B3dmego._Ul._D%C4%85browskiego_Wroc%C5%82aw_RN2.jpg', false, true, 16),
  ('Fellowship hall set for a shared meal, Adventist church, Brussels', '/images/gallery/interiors-lit-timber.webp', '/images/gallery/interiors-lit-timber-sm.webp', 'interiors', 2400, 1600, 'Angel Marcuello', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Salle_polyvalent.jpg', false, true, 17),
  ('Kyambogo Seventh-day Adventist Church, Kampala — the tower', '/images/gallery/interiors-light-beam.webp', '/images/gallery/interiors-light-beam-sm.webp', 'architecture', 2400, 2307, 'Ssemmanda will', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Kyambogo_Seventh_Day_Adventist_Church_02.jpg', true, true, 18),
  ('Sanctuary of the Adventist church in Wrocław, Poland', '/images/gallery/interiors-light-rays.webp', '/images/gallery/interiors-light-rays-sm.webp', 'interiors', 2400, 1351, 'Argonowski', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:Zb%C3%B3r_Adwentyst%C3%B3w_Dnia_Si%C3%B3dmego_Wroc%C5%82aw.jpg', false, true, 19),
  ('Community outreach day at Bukongo SDA Church, Iganga, Uganda', '/images/gallery/interiors-long-nave.webp', '/images/gallery/interiors-long-nave-sm.webp', 'outreach', 2400, 1594, 'USAID in Africa', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Uganda_Nutrition_(26941732297).jpg', false, true, 20),
  ('Sabbath worship at Laurel Maranatha SDA Church, Maryland', '/images/gallery/interiors-stone-pews.webp', '/images/gallery/interiors-stone-pews-sm.webp', 'community', 2400, 1212, 'User:Youngballerrr', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Laurel_Maranatha_Spanish_SDA_2014-06-24_00-44.jpg', false, true, 21),
  ('Carrying a block to the site', '/images/gallery/construction-carrying-block.webp', '/images/gallery/construction-carrying-block-sm.webp', 'construction', 2400, 1600, 'Biva2017', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Construction-women.jpg', true, true, 22),
  ('Every stone carried by hand', '/images/gallery/construction-carrying-stone.webp', '/images/gallery/construction-carrying-stone-sm.webp', 'construction', 2400, 1600, 'Biva2017', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Slum_construction.jpg', false, true, 23),
  ('Blockwork walls taking shape', '/images/gallery/construction-blockwork.webp', '/images/gallery/construction-blockwork-sm.webp', 'construction', 2400, 1800, 'Africa1718', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Construction_Of_Office_in_Kenya.jpg', false, true, 24),
  ('Laying blocks course by course', '/images/gallery/construction-laying-blocks.webp', '/images/gallery/construction-laying-blocks-sm.webp', 'construction', 2400, 1607, 'Okhaifo', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Bricklayer_at_work.jpg', false, true, 25),
  ('Mixing mortar on site', '/images/gallery/construction-mixing-mortar.webp', '/images/gallery/construction-mixing-mortar-sm.webp', 'construction', 2005, 2400, 'Albertoblaq', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Bricklaying.png', false, true, 26),
  ('Light through a new window opening', '/images/gallery/construction-window-light.webp', '/images/gallery/construction-window-light-sm.webp', 'construction', 2400, 2067, 'Kimathinjoki', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Turbaned_mason.jpg', false, true, 27),
  ('Maranatha volunteers building a one-day church, Chiapas, Mexico', '/images/gallery/construction-rising-frame.webp', '/images/gallery/construction-rising-frame-sm.webp', 'construction', 2400, 1800, 'Sdenny123', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Maranatha_church_Bebedero_Chiapas_Mexico.jpg', false, true, 28),
  ('Setting the foundation', '/images/gallery/construction-foundation.webp', '/images/gallery/construction-foundation-sm.webp', 'construction', 2400, 1607, 'Kenogenic', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Nigerian_bricklayers_(4).jpg', false, true, 29),
  ('Church attic under renovation, Adventist church, Wrocław', '/images/gallery/renovation-scaffold-interior.webp', '/images/gallery/renovation-scaffold-interior-sm.webp', 'renovation', 2400, 1599, 'Robert Niedźwiedzki', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Poddasze_ko%C5%9Bcio%C5%82a_Adwentyst%C3%B3w_Dnia_Si%C3%B3dmego._%C5%9Aciana_od_ul._D%C4%85browskiego._Wroc%C5%82aw.jpg', false, true, 30),
  ('Roof timbers exposed during renovation, Wrocław', '/images/gallery/renovation-scaffold-arches.webp', '/images/gallery/renovation-scaffold-arches-sm.webp', 'renovation', 2400, 1600, 'Robert Niedźwiedzki', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Poddasze_ko%C5%9Bcio%C5%82a_Adwentyst%C3%B3w_Dnia_Si%C3%B3dmego._Ul._D%C4%85browskiego_Wroc%C5%82aw.jpg', false, true, 31),
  ('Restoring historic brickwork', '/images/gallery/renovation-brick-restoration.webp', '/images/gallery/renovation-brick-restoration-sm.webp', 'renovation', 2400, 1800, 'MOs810', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MOs810,_WG_2016_47,_Dolnoslaskie_Zakamarki_III_(Saint_Lazarus_church_in_Wroc%C5%82aw,_renovatio_2016).jpg', false, true, 32),
  ('An arched window in the attic during renovation, Wrocław', '/images/gallery/renovation-scaffold-wall.webp', '/images/gallery/renovation-scaffold-wall-sm.webp', 'renovation', 1599, 2400, 'Robert Niedźwiedzki', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Poddasze_ko%C5%9Bcio%C5%82a_Adwentyst%C3%B3w_Dnia_Si%C3%B3dmego._Okno_w_%C5%9Bcianie_od_ul._D%C4%85browskiego._Wroc%C5%82aw.jpg', false, true, 33),
  ('An open Bible on its stand', '/images/gallery/details-bible-stand.webp', '/images/gallery/details-bible-stand-sm.webp', 'details', 2400, 1594, 'Wilfredor', 'CC0', 'https://commons.wikimedia.org/wiki/File:Open_Bible_in_the_Church_of_the_ports_of_Altagracia.jpg', false, true, 34),
  ('Scripture and study', '/images/gallery/details-bible-pen.webp', '/images/gallery/details-bible-pen-sm.webp', 'details', 2400, 1600, 'Ryk Neethling from Melbourne, Australia', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Open_Bible_with_pen_(4543060842).jpg', false, true, 35),
  ('Pews in afternoon light', '/images/gallery/details-pews-light.webp', '/images/gallery/details-pews-light-sm.webp', 'details', 2400, 1600, 'Acabashi', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Beauchamp_Roding_-_St_Botolph%27s_Church_-_Essex_England_-_nave_north_tiered_oak_pews.jpg', false, true, 36),
  ('Light across cast concrete', '/images/gallery/details-concrete-detail.webp', '/images/gallery/details-concrete-detail-sm.webp', 'details', 2400, 2400, 'seier+seier', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Gottfried_b%C3%B6hm,_kolumba_chapel_extension_1956_(3460863882).jpg', false, true, 37),
  ('The open Word', '/images/gallery/details-open-bible.webp', '/images/gallery/details-open-bible-sm.webp', 'details', 2400, 1800, 'Leon Brooks', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Holy_bible_book.jpg', false, true, 38),
  ('Seventh-day Adventist members and families gathered together', '/images/gallery/community-congregation.webp', '/images/gallery/community-congregation-sm.webp', 'community', 2400, 1002, 'Gaigiel', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Photo_of_different_family_gathering_as_good_day_for_sda_members._Jpg.jpg', false, true, 39),
  ('Closing service, Pathfinder Camporee 2023, Hungary', '/images/gallery/community-full-sanctuary.webp', '/images/gallery/community-full-sanctuary-sm.webp', 'community', 2400, 1600, 'Tor Tjeransen', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:TED_Pathfinder_Camporee_2023_1.jpg', false, true, 40),
  ('TUCASA choir, University of Dar es Salaam, Tanzania', '/images/gallery/community-choir.webp', '/images/gallery/community-choir-sm.webp', 'community', 2400, 1800, 'Eliud pzos', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:TUCASA_UDSM.jpg', true, true, 41),
  ('Pathfinder club, Córdoba, Argentina', '/images/gallery/community-children-service.webp', '/images/gallery/community-children-service-sm.webp', 'community', 2400, 1350, 'Joaquinosidad', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:ChampaConquistadores.jpg', false, true, 42),
  ('Pathfinder camporee worship, São Paulo, Brazil', '/images/gallery/community-prayer.webp', '/images/gallery/community-prayer-sm.webp', 'community', 2048, 1536, 'Elcio Ferreira', 'CC BY-SA 2.0', 'https://commons.wikimedia.org/wiki/File:Campori_de_Desbravadores_em_2009.jpg', false, true, 43),
  ('Adventist youth camp, Nguengue, Angola', '/images/gallery/community-walking-together.webp', '/images/gallery/community-walking-together-sm.webp', 'community', 2400, 1793, 'Iasd Viana 2', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Acampamento_do_nguengue.jpg', false, true, 44),
  ('A Seventh-day Adventist baptism', '/images/gallery/community-communion.webp', '/images/gallery/community-communion-sm.webp', 'community', 1920, 1152, 'ABEREZACHARY', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:SEVENTH_DAY_ADVENTIST_BAPTISM.jpg', false, true, 45),
  ('Joy that outlasts walls', '/images/gallery/outreach-smiling-child.webp', '/images/gallery/outreach-smiling-child-sm.webp', 'outreach', 2400, 1600, 'Trocaire from Ireland', 'CC BY 2.0', 'https://commons.wikimedia.org/wiki/File:Kibera13_(Kenya_1)_(7180347921).jpg', true, true, 46),
  ('A shared meal', '/images/gallery/outreach-shared-meal.webp', '/images/gallery/outreach-shared-meal-sm.webp', 'outreach', 2400, 1800, 'Nicor', 'CC BY-SA 3.0', 'https://commons.wikimedia.org/wiki/File:Nyota,_Kenya_02.jpg', false, true, 47),
  ('A classroom full of possibility', '/images/gallery/outreach-classroom.webp', '/images/gallery/outreach-classroom-sm.webp', 'outreach', 2400, 1594, 'D. Willetts', 'CC BY-SA 3.0 igo', 'https://commons.wikimedia.org/wiki/File:(2011_Education_for_All_Global_Monitoring_Report)_-School_children_in_Kakuma_refugee_camp,_Kenya_1.jpg', false, true, 48),
  ('Children running across the field', '/images/gallery/outreach-running-children.webp', '/images/gallery/outreach-running-children-sm.webp', 'outreach', 2400, 1349, 'Onlyonestef', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Girls_compete_in_a_7_lap_race_during_high_school_first_term_games_in_Machakos,_Kenya.jpg', false, true, 49),
  ('Neighbours gathering outdoors', '/images/gallery/outreach-gathering.webp', '/images/gallery/outreach-gathering-sm.webp', 'outreach', 2400, 1800, 'Agoni Abraham', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Volunteers_in_Africa.jpg', false, true, 50),
  ('Schoolchildren together', '/images/gallery/outreach-school-children.webp', '/images/gallery/outreach-school-children-sm.webp', 'outreach', 2400, 1800, 'Oertherdb', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:School_children_amazed_by_flowing_water_from_pipe_stand_in_Otho_Abwao_Kenya.jpg', false, true, 51),
  ('A young learner at his desk', '/images/gallery/outreach-young-learner.webp', '/images/gallery/outreach-young-learner-sm.webp', 'outreach', 2400, 1594, 'Master Sgt. Jeremy Lock', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Community_Assistance_Volunteers_DVIDS96949.jpg', false, true, 52),
  ('Volunteers making building blocks', '/images/gallery/volunteers-block-making.webp', '/images/gallery/volunteers-block-making-sm.webp', 'volunteers', 1800, 2400, 'Goodymeraj', 'CC BY 4.0', 'https://commons.wikimedia.org/wiki/File:A_bricklayer_moulding_blocks.jpg', false, true, 53),
  ('Volunteers painting a classroom', '/images/gallery/volunteers-painting.webp', '/images/gallery/volunteers-painting-sm.webp', 'volunteers', 2400, 1463, 'Master Sgt. Jeremy Lock', 'Public domain', 'https://commons.wikimedia.org/wiki/File:Community_Assistance_Volunteers_DVIDS96943.jpg', false, true, 54);

-- Demonstration projects (clearly labelled on the website).
with p as (
  insert into public.projects (title, slug, summary, description, category, location, status, cover_image, objectives, featured, published, is_demo) values
  ('New Sanctuary Construction', 'demo-new-sanctuary', 'Sample layout for a ground-up church construction project.', 'This is a demonstration entry that shows how a construction project will appear on the website. Once the organisation publishes a real project from the admin dashboard, its verified description, location, photographs and progress updates will replace this text.', 'construction', 'Location to be confirmed', 'ongoing', '/images/gallery/construction-rising-frame.webp', array['Example objective — complete foundation and structural frame','Example objective — enclose the building and install roofing','Example objective — finish interior and dedicate the sanctuary'], true, true, true),
  ('Sanctuary Renovation', 'demo-sanctuary-renovation', 'Sample layout for restoring an existing church building.', 'A demonstration renovation project. Real renovation projects will document the condition of the existing structure, the planned works and verified progress, all managed from the admin dashboard.', 'renovation', 'Location to be confirmed', 'planned', '/images/gallery/renovation-scaffold-arches.webp', array['Example objective — structural assessment','Example objective — roof and wall repairs','Example objective — interior refurbishment'], true, true, true),
  ('Community Outreach Programme', 'demo-community-outreach-centre', 'Sample layout for a church-led community initiative.', 'A demonstration community initiative. This is where the organisation will describe real outreach programmes run through partner congregations once details are published.', 'community', 'Location to be confirmed', 'planned', '/images/gallery/outreach-shared-meal.webp', array['Example objective — identify community needs with the local church','Example objective — launch the programme'], true, true, true),
  ('Chapel Completion', 'demo-completed-chapel', 'Sample layout for a completed project.', 'A demonstration of how a completed project and its dedication will be presented.', 'construction', 'Location to be confirmed', 'completed', '/images/gallery/interiors-timber-cross.webp', array['Example objective — dedication service'], false, true, true)
  returning id, slug
)
insert into public.project_images (project_id, image_url, caption, display_order)
select p.id, i.url, 'Illustrative image', i.ord from p join (values
  ('demo-new-sanctuary', '/images/gallery/construction-laying-blocks.webp', 0),
  ('demo-new-sanctuary', '/images/gallery/construction-blockwork.webp', 1),
  ('demo-new-sanctuary', '/images/gallery/construction-mixing-mortar.webp', 2),
  ('demo-new-sanctuary', '/images/gallery/construction-foundation.webp', 3),
  ('demo-sanctuary-renovation', '/images/gallery/renovation-scaffold-interior.webp', 0),
  ('demo-sanctuary-renovation', '/images/gallery/renovation-brick-restoration.webp', 1),
  ('demo-sanctuary-renovation', '/images/gallery/renovation-scaffold-wall.webp', 2)
) as i(slug, url, ord) on i.slug = p.slug;

insert into public.project_updates (project_id, title, content)
select id, 'Example update', 'Project updates published from the admin dashboard will appear here as a timeline, with optional photographs.'
from public.projects where slug = 'demo-new-sanctuary';

-- Starter FAQs (mirrors src/data/faqs.ts; edit them in Admin → FAQs).
insert into public.faqs (category, question, answer, display_order) values
  ('About us', 'What is Golden Blocks Mission?', 'A nonprofit Christian organisation that builds and renovates churches and supports the Gospel, working with the Seventh-day Adventist Church in the North East Kenya Field.', 1),
  ('About us', 'What does the name “Golden Blocks” mean?', 'Gold is our finest, freely offered to God. Blocks are the material of His house.', 2),
  ('Giving', 'How can I give?', 'On the Donate page: M-Pesa, Visa or Mastercard, or bank transfer.', 3),
  ('Giving', 'Is giving online secure?', 'Yes. Cards are processed by Paystack, and each gift is confirmed by the payment provider before it is recorded.', 4),
  ('Giving', 'Can I choose what my gift supports?', 'Yes. Choose an area of work or a specific project when you give.', 5),
  ('Giving', 'Can I give every month?', 'Yes, by card. M-Pesa gifts are one-time.', 6),
  ('Giving', 'Will I receive a receipt?', 'You get a confirmation email once your payment is verified. Official receipts: to be confirmed.', 7),
  ('Getting involved', 'How else can I help besides giving money?', 'Give materials, volunteer, offer professional skills, fundraise or pray. See Get Involved.', 8),
  ('Getting involved', 'Can my church or business partner with you?', 'Yes. Send a partnership enquiry and our team will reply.', 9),
  ('Getting involved', 'How does sponsorship work?', 'Choose a programme on the Sponsorship page and send an enquiry.', 10),
  ('Projects', 'How can I follow a project’s progress?', 'Each project page has photos and progress updates.', 11),
  ('Contact', 'How do I contact the team?', 'Use the form on the Contact page.', 12);
